/* Generated by tools/generate_profile_headers.py.
 * SIMULATION ONLY: gravity, load, coordinate signs and joint limits
 * must be identified/verified for your hardware. No automatic enable. */
#ifndef GM6020_PITCH_SIMULATION_CONFIG_H
#define GM6020_PITCH_SIMULATION_CONFIG_H
#include "gimbal_controller.h"

static inline GimbalConfig gm6020_pitch_simulation_config(void)
{
    const GimbalConfig config = {
        .control = {
            .inertia_kg_m2 = 0.039f,
            .damping_nm_s_rad = 0.3f,
            .k_position = 85.87696424f,
            .k_velocity = 3.07876864f,
            .k_integral = 171.7539285f,
            .integral_limit_nm = 0.2f,
            .antiwindup_rate_s = 2.0f,
            .coulomb_nm = 0.0f,
            .coulomb_velocity_rad_s = 0.04f,
            .eso_bandwidth_rad_s = 80.0f,
            .eso_gain = 0.8f,
            .disturbance_limit_nm = 1.2f,
            .compensation_limit_nm = 0.4f,
            .compensation_slew_nm_s = 40.0f,
            .torque_limit_nm = 1.2f,
            .torque_slew_nm_s = 100.0f,
            .dt_min_s = 0.0005f,
            .dt_max_s = 0.002f,
            .feedback_timeout_s = 0.005f,
            .reference_timeout_s = 0.005f,
            .position_min_rad = -3.141592654f,
            .position_max_rad = 3.141592654f,
            .velocity_limit_rad_s = 33.5f,
            .tracking_error_limit_rad = 0.436332313f,
            .velocity_error_filter_tau_s = 0.0f,
        },
        .gravity_cos_nm = 0.45f,
        .gravity_sin_nm = 0.1f,
        .joint_min_rad = -0.436332313f,
        .joint_max_rad = 0.7853981634f,
        .joint_margin_rad = 0.01745329252f,
        .pitch_enabled = true,
    };
    return config;
}
#endif
