/* Generated by tools/generate_profile_headers.py; edit JSON files in profiles/.
 * SIMULATION ONLY: identify your actual load and validate motor limits
 * before adapting this configuration to hardware. No automatic enable. */
#ifndef GM6020_SIMULATION_CONFIG_H
#define GM6020_SIMULATION_CONFIG_H
#include "yaw_controller.h"

static inline YawConfig gm6020_simulation_config(void)
{
    const YawConfig config = {
        .inertia_kg_m2 = 0.039f,
        .damping_nm_s_rad = 0.3f,
        .k_position = 85.87696424f,
        .k_velocity = 3.07876864f,
        .k_integral = 171.7539285f,
        .integral_limit_nm = 0.2f,
        .antiwindup_rate_s = 2.0f,
        .coulomb_nm = 0.0f,
        .coulomb_velocity_rad_s = 0.04f,
        .eso_bandwidth_rad_s = 80.0f,
        .eso_gain = 0.8f,
        .disturbance_limit_nm = 1.2f,
        .compensation_limit_nm = 0.4f,
        .compensation_slew_nm_s = 40.0f,
        .torque_limit_nm = 1.2f,
        .torque_slew_nm_s = 100.0f,
        .dt_min_s = 0.0005f,
        .dt_max_s = 0.002f,
        .feedback_timeout_s = 0.005f,
        .reference_timeout_s = 0.005f,
        .position_min_rad = -3.141592654f,
        .position_max_rad = 3.141592654f,
        .velocity_limit_rad_s = 33.5f,
        .tracking_error_limit_rad = 3.141592654f,
        .velocity_error_filter_tau_s = 0.0f,
    };
    return config;
}
#endif
