"""Generate copyable C configuration examples from simulation-only JSON profiles."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROFILES = {"dm4310": "dm4310_24v.json", "gm6020": "gm6020_current.json"}


def render(name, profile):
    if profile.get("simulation_only") is not True:
        raise ValueError("Only explicitly simulation-only profiles belong in these examples")
    guard = name.upper() + "_SIMULATION_CONFIG_H"
    lines = ["/* Generated by tools/generate_profile_headers.py; edit JSON files in profiles/.",
             " * SIMULATION ONLY: identify your actual load and validate motor limits",
             " * before adapting this configuration to hardware. No automatic enable. */",
             f"#ifndef {guard}", f"#define {guard}", '#include "yaw_controller.h"', "",
             f"static inline YawConfig {name}_simulation_config(void)", "{",
             "    const YawConfig config = {"]
    for key, value in profile["controller"].items():
        token = format(value, ".10g")
        if "." not in token and "e" not in token:
            token += ".0"
        lines.append(f"        .{key} = {token}f,")
    return "\n".join(lines + ["    };", "    return config;", "}", "#endif", ""])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if committed headers are stale")
    args = parser.parse_args()
    for name, filename in PROFILES.items():
        profile = json.loads((ROOT / "profiles" / filename).read_text())
        path = ROOT / "variants" / name / "simulation_config.h"
        content = render(name, profile)
        if args.check:
            if not path.is_file() or path.read_text() != content:
                raise SystemExit(f"stale generated profile: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
        print(f"{'Checked' if args.check else 'Generated'} {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
