"""Generate copyable C configuration examples from simulation-only JSON profiles."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROFILES = {"dm4310": "dm4310_24v.json", "gm6020": "gm6020_current.json"}


def c_float(value):
    token = format(value, ".10g")
    if "." not in token and "e" not in token:
        token += ".0"
    return token + "f"


def render(name, profile):
    if profile.get("simulation_only") is not True:
        raise ValueError("Only explicitly simulation-only profiles belong in these examples")
    guard = name.upper() + "_SIMULATION_CONFIG_H"
    lines = ["/* Generated by tools/generate_profile_headers.py; edit JSON files in profiles/.",
             " * SIMULATION ONLY: identify your actual load and validate motor limits",
             " * before adapting this configuration to hardware. No automatic enable. */",
             f"#ifndef {guard}", f"#define {guard}", '#include "yaw_controller.h"', "",
             f"static inline YawConfig {name}_simulation_config(void)", "{",
             "    const YawConfig config = {"]
    for key, value in profile["controller"].items():
        lines.append(f"        .{key} = {c_float(value)},")
    return "\n".join(lines + ["    };", "    return config;", "}", "#endif", ""])


def render_pitch(name, profile, base):
    if profile.get("simulation_only") is not True or base.get("simulation_only") is not True:
        raise ValueError("Pitch examples must remain explicitly simulation-only")
    control = {**base["controller"], **profile["controller_overrides"]}
    guard = name.upper() + "_PITCH_SIMULATION_CONFIG_H"
    lines = ["/* Generated by tools/generate_profile_headers.py.",
             " * SIMULATION ONLY: gravity, load, coordinate signs and joint limits",
             " * must be identified/verified for your hardware. No automatic enable. */",
             f"#ifndef {guard}", f"#define {guard}", '#include "gimbal_controller.h"', "",
             f"static inline GimbalConfig {name}_pitch_simulation_config(void)", "{",
             "    const GimbalConfig config = {", "        .control = {"]
    lines += [f"            .{key} = {c_float(value)}," for key, value in control.items()]
    fields = {"gravity_cos_nm": profile["gravity_model"]["cos_nm"],
              "gravity_sin_nm": profile["gravity_model"]["sin_nm"],
              "joint_min_rad": profile["plant_assumptions"]["physical_min_rad"],
              "joint_max_rad": profile["plant_assumptions"]["physical_max_rad"],
              "joint_margin_rad": profile["joint_margin_rad"]}
    lines += ["        },"] + [f"        .{key} = {c_float(value)}," for key, value in fields.items()]
    return "\n".join(lines + ["        .pitch_enabled = true,", "    };", "    return config;",
                               "}", "#endif", ""])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if committed headers are stale")
    args = parser.parse_args()
    for name, filename in PROFILES.items():
        profile = json.loads((ROOT / "profiles" / filename).read_text())
        path = ROOT / "variants" / name / "simulation_config.h"
        content = render(name, profile)
        if args.check:
            if not path.is_file() or path.read_text() != content:
                raise SystemExit(f"stale generated profile: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
        print(f"{'Checked' if args.check else 'Generated'} {path.relative_to(ROOT)}")
        pitch = json.loads((ROOT / "profiles" / filename.replace(".json", "_pitch.json")).read_text())
        if pitch["motor_profile"] != filename:
            raise ValueError("Pitch profile motor source mismatch")
        path = path.with_name("pitch_simulation_config.h")
        content = render_pitch(name, pitch, profile)
        if args.check:
            if not path.is_file() or path.read_text() != content:
                raise SystemExit(f"stale generated profile: {path}")
        else:
            path.write_text(content)
        print(f"{'Checked' if args.check else 'Generated'} {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
